//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalyzerRevit.Analyzer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalyzerRevit.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Emial.
        /// </summary>
        public static string _Preview {
            get {
                return ResourceManager.GetString("_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [m2].
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string DaylightCustom {
            get {
                return ResourceManager.GetString("DaylightCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True North.
        /// </summary>
        public static string DaylightCustom_TrueNorth {
            get {
                return ResourceManager.GetString("DaylightCustom_TrueNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [m].
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [°].
        /// </summary>
        public static string LocationDegree {
            get {
                return ResourceManager.GetString("LocationDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [°].
        /// </summary>
        public static string LocationDegree1 {
            get {
                return ResourceManager.GetString("LocationDegree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationOnEarth {
            get {
                return ResourceManager.GetString("LocationOnEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location on map.
        /// </summary>
        public static string LocationOnEarth_CheckLocation {
            get {
                return ResourceManager.GetString("LocationOnEarth_CheckLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string LocationOnEarth_CheckLocationButton {
            get {
                return ResourceManager.GetString("LocationOnEarth_CheckLocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string LocationOnEarth_Latitude {
            get {
                return ResourceManager.GetString("LocationOnEarth_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string LocationOnEarth_Longitude {
            get {
                return ResourceManager.GetString("LocationOnEarth_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string PageInput_ElementsInputButton {
            get {
                return ResourceManager.GetString("PageInput_ElementsInputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string PageInput_ElementsInputShowButton {
            get {
                return ResourceManager.GetString("PageInput_ElementsInputShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently selected:.
        /// </summary>
        public static string PageInput_ElementsInputShowText {
            get {
                return ResourceManager.GetString("PageInput_ElementsInputShowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements to analyze.
        /// </summary>
        public static string PageInput_ElementsInputText {
            get {
                return ResourceManager.GetString("PageInput_ElementsInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string PageInput_SurroundingsInputButton {
            get {
                return ResourceManager.GetString("PageInput_SurroundingsInputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shading elements.
        /// </summary>
        public static string PageInput_SurroundingsInputText {
            get {
                return ResourceManager.GetString("PageInput_SurroundingsInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string PageInput_SurroundingsShowButton {
            get {
                return ResourceManager.GetString("PageInput_SurroundingsShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently selected:.
        /// </summary>
        public static string PageInput_SurroundingsShowText {
            get {
                return ResourceManager.GetString("PageInput_SurroundingsShowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzis Results.
        /// </summary>
        public static string PageOutput_AnalyzisResults {
            get {
                return ResourceManager.GetString("PageOutput_AnalyzisResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked elements.
        /// </summary>
        public static string PageOutput_AnalyzisScore {
            get {
                return ResourceManager.GetString("PageOutput_AnalyzisScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzis total score.
        /// </summary>
        public static string PageOutput_AnalyzisTotalScore {
            get {
                return ResourceManager.GetString("PageOutput_AnalyzisTotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create schedule.
        /// </summary>
        public static string PageOutput_CreateScheduleButton {
            get {
                return ResourceManager.GetString("PageOutput_CreateScheduleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D results.
        /// </summary>
        public static string PageOutput_DisplayAnalyzisResult2D {
            get {
                return ResourceManager.GetString("PageOutput_DisplayAnalyzisResult2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D results.
        /// </summary>
        public static string PageOutput_DisplayAnalyzisResult3D {
            get {
                return ResourceManager.GetString("PageOutput_DisplayAnalyzisResult3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display results.
        /// </summary>
        public static string PageOutput_DisplayHeader {
            get {
                return ResourceManager.GetString("PageOutput_DisplayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements failed.
        /// </summary>
        public static string PageOutput_ElementsFailed {
            get {
                return ResourceManager.GetString("PageOutput_ElementsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string PageOutput_ElementsFailedButton {
            get {
                return ResourceManager.GetString("PageOutput_ElementsFailedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??.
        /// </summary>
        public static string PageOutput_ElementsInputText {
            get {
                return ResourceManager.GetString("PageOutput_ElementsInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements passed.
        /// </summary>
        public static string PageOutput_ElementsPassed {
            get {
                return ResourceManager.GetString("PageOutput_ElementsPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string PageOutput_ElementsPassedSelecteButton {
            get {
                return ResourceManager.GetString("PageOutput_ElementsPassedSelecteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create graphics.
        /// </summary>
        public static string PageOutput_SaveGraphicalButton {
            get {
                return ResourceManager.GetString("PageOutput_SaveGraphicalButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [deg].
        /// </summary>
        public static string Radians {
            get {
                return ResourceManager.GetString("Radians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestValue.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Email.
        /// </summary>
        public static string UserData_EmailPreview {
            get {
                return ResourceManager.GetString("UserData_EmailPreview", resourceCulture);
            }
        }
    }
}
