//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticatorStandalone....AuthenticatorConnector.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthenticatorStandalone.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Test Emial.
        /// </summary>
        public static string _Preview {
            get {
                return ResourceManager.GetString("_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [m2].
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Location.
        /// </summary>
        public static string DaylightCustom {
            get {
                return ResourceManager.GetString("DaylightCustom", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu True North.
        /// </summary>
        public static string DaylightCustom_TrueNorth {
            get {
                return ResourceManager.GetString("DaylightCustom_TrueNorth", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [m].
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [°].
        /// </summary>
        public static string LocationDegree {
            get {
                return ResourceManager.GetString("LocationDegree", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [°].
        /// </summary>
        public static string LocationDegree1 {
            get {
                return ResourceManager.GetString("LocationDegree1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Location.
        /// </summary>
        public static string LocationOnEarth {
            get {
                return ResourceManager.GetString("LocationOnEarth", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Location on map.
        /// </summary>
        public static string LocationOnEarth_CheckLocation {
            get {
                return ResourceManager.GetString("LocationOnEarth_CheckLocation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Check.
        /// </summary>
        public static string LocationOnEarth_CheckLocationButton {
            get {
                return ResourceManager.GetString("LocationOnEarth_CheckLocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Latitude.
        /// </summary>
        public static string LocationOnEarth_Latitude {
            get {
                return ResourceManager.GetString("LocationOnEarth_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Longitude.
        /// </summary>
        public static string LocationOnEarth_Longitude {
            get {
                return ResourceManager.GetString("LocationOnEarth_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select.
        /// </summary>
        public static string PageInput_ElementsInputButton {
            get {
                return ResourceManager.GetString("PageInput_ElementsInputButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show.
        /// </summary>
        public static string PageInput_ElementsInputShowButton {
            get {
                return ResourceManager.GetString("PageInput_ElementsInputShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Currently selected:.
        /// </summary>
        public static string PageInput_ElementsInputShowText {
            get {
                return ResourceManager.GetString("PageInput_ElementsInputShowText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Elements to analyze.
        /// </summary>
        public static string PageInput_ElementsInputText {
            get {
                return ResourceManager.GetString("PageInput_ElementsInputText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select.
        /// </summary>
        public static string PageInput_SurroundingsInputButton {
            get {
                return ResourceManager.GetString("PageInput_SurroundingsInputButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Shading elements.
        /// </summary>
        public static string PageInput_SurroundingsInputText {
            get {
                return ResourceManager.GetString("PageInput_SurroundingsInputText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show.
        /// </summary>
        public static string PageInput_SurroundingsShowButton {
            get {
                return ResourceManager.GetString("PageInput_SurroundingsShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Currently selected:.
        /// </summary>
        public static string PageInput_SurroundingsShowText {
            get {
                return ResourceManager.GetString("PageInput_SurroundingsShowText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Analyzis Results.
        /// </summary>
        public static string PageOutput_AnalyzisResults {
            get {
                return ResourceManager.GetString("PageOutput_AnalyzisResults", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Checked elements.
        /// </summary>
        public static string PageOutput_AnalyzisScore {
            get {
                return ResourceManager.GetString("PageOutput_AnalyzisScore", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Analyzis total score.
        /// </summary>
        public static string PageOutput_AnalyzisTotalScore {
            get {
                return ResourceManager.GetString("PageOutput_AnalyzisTotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create schedule.
        /// </summary>
        public static string PageOutput_CreateScheduleButton {
            get {
                return ResourceManager.GetString("PageOutput_CreateScheduleButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 2D results.
        /// </summary>
        public static string PageOutput_DisplayAnalyzisResult2D {
            get {
                return ResourceManager.GetString("PageOutput_DisplayAnalyzisResult2D", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show Rays  - use carefully !.
        /// </summary>
        public static string PageOutput_DisplayAnalyzisResult3D {
            get {
                return ResourceManager.GetString("PageOutput_DisplayAnalyzisResult3D", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Display results.
        /// </summary>
        public static string PageOutput_DisplayHeader {
            get {
                return ResourceManager.GetString("PageOutput_DisplayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Elements failed.
        /// </summary>
        public static string PageOutput_ElementsFailed {
            get {
                return ResourceManager.GetString("PageOutput_ElementsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select.
        /// </summary>
        public static string PageOutput_ElementsFailedButton {
            get {
                return ResourceManager.GetString("PageOutput_ElementsFailedButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ??.
        /// </summary>
        public static string PageOutput_ElementsInputText {
            get {
                return ResourceManager.GetString("PageOutput_ElementsInputText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Elements passed.
        /// </summary>
        public static string PageOutput_ElementsPassed {
            get {
                return ResourceManager.GetString("PageOutput_ElementsPassed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select.
        /// </summary>
        public static string PageOutput_ElementsPassedSelecteButton {
            get {
                return ResourceManager.GetString("PageOutput_ElementsPassedSelecteButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Height of shading object - relative to sample.
        /// </summary>
        public static string PageOutput_Height {
            get {
                return ResourceManager.GetString("PageOutput_Height", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create graphics.
        /// </summary>
        public static string PageOutput_SaveGraphicalButton {
            get {
                return ResourceManager.GetString("PageOutput_SaveGraphicalButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [deg].
        /// </summary>
        public static string Radians {
            get {
                return ResourceManager.GetString("Radians", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu %.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu TestValue.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Test.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Test Email.
        /// </summary>
        public static string UserData_EmailPreview {
            get {
                return ResourceManager.GetString("UserData_EmailPreview", resourceCulture);
            }
        }
    }
}
