//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticatorWPFLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthenticatorWPFLibrary.Resources.LocalizationUser", typeof(LocalizationUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am working. It&apos;s coffee time for you..
        /// </summary>
        public static string CommunicationWaitingLong {
            get {
                return ResourceManager.GetString("CommunicationWaitingLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report bug.
        /// </summary>
        public static string FooterBugReport {
            get {
                return ResourceManager.GetString("FooterBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kolega.space.
        /// </summary>
        public static string FooterKolegaSite {
            get {
                return ResourceManager.GetString("FooterKolegaSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add suggestion.
        /// </summary>
        public static string FooterSurveySuggestion {
            get {
                return ResourceManager.GetString("FooterSurveySuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide.
        /// </summary>
        public static string FooterUserGuide {
            get {
                return ResourceManager.GetString("FooterUserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string GoToProfile {
            get {
                return ResourceManager.GetString("GoToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In with Apple.
        /// </summary>
        public static string ModalLogin_ButtonAppleLogin {
            get {
                return ResourceManager.GetString("ModalLogin_ButtonAppleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ModalLogin_ButtonChangePassword {
            get {
                return ResourceManager.GetString("ModalLogin_ButtonChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In with Google.
        /// </summary>
        public static string ModalLogin_ButtonGoogleLogin {
            get {
                return ResourceManager.GetString("ModalLogin_ButtonGoogleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string ModalLogin_ButtonLogin {
            get {
                return ResourceManager.GetString("ModalLogin_ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing up.
        /// </summary>
        public static string ModalLogin_ButtonSignUp {
            get {
                return ResourceManager.GetString("ModalLogin_ButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ModalLogin_ChangePasswordText {
            get {
                return ResourceManager.GetString("ModalLogin_ChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account yet?.
        /// </summary>
        public static string ModalLogin_SignUpText {
            get {
                return ResourceManager.GetString("ModalLogin_SignUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing in to your account.
        /// </summary>
        public static string ModalLogin_SubTitle {
            get {
                return ResourceManager.GetString("ModalLogin_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string ModalLogin_Text1 {
            get {
                return ResourceManager.GetString("ModalLogin_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string ModalLogin_Title {
            get {
                return ResourceManager.GetString("ModalLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to login.
        /// </summary>
        public static string ModalPasswordChanged_ButtonGoBackToLogin {
            get {
                return ResourceManager.GetString("ModalPasswordChanged_ButtonGoBackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email inbox. Follow the link and set a new password following the instructions in the message from us..
        /// </summary>
        public static string ModalPasswordChanged_CheckEmailText {
            get {
                return ResourceManager.GetString("ModalPasswordChanged_CheckEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent you an email to change your password..
        /// </summary>
        public static string ModalPasswordChanged_SubTitle {
            get {
                return ResourceManager.GetString("ModalPasswordChanged_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ModalPasswordChanged_Title {
            get {
                return ResourceManager.GetString("ModalPasswordChanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string ModalRegister_ButtonCancle {
            get {
                return ResourceManager.GetString("ModalRegister_ButtonCancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string ModalRegister_ButtonRegister {
            get {
                return ResourceManager.GetString("ModalRegister_ButtonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account!.
        /// </summary>
        public static string ModalRegister_SubTitle {
            get {
                return ResourceManager.GetString("ModalRegister_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string ModalRegister_Title {
            get {
                return ResourceManager.GetString("ModalRegister_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to login.
        /// </summary>
        public static string ModalRegistered_ButtonGoBackToLogin {
            get {
                return ResourceManager.GetString("ModalRegistered_ButtonGoBackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string ModalRegistered_ButtonSendAgain {
            get {
                return ResourceManager.GetString("ModalRegistered_ButtonSendAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email for a verification link and log in..
        /// </summary>
        public static string ModalRegistered_CheckEmailText {
            get {
                return ResourceManager.GetString("ModalRegistered_CheckEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haven&apos;t recived verification email?.
        /// </summary>
        public static string ModalRegistered_NoEmailRevicedText {
            get {
                return ResourceManager.GetString("ModalRegistered_NoEmailRevicedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification email sent.
        /// </summary>
        public static string ModalRegistered_SubTitle {
            get {
                return ResourceManager.GetString("ModalRegistered_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet your new Kolega!.
        /// </summary>
        public static string ModalRegistered_Title {
            get {
                return ResourceManager.GetString("ModalRegistered_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string TopBar_ViewMode_Advanced {
            get {
                return ResourceManager.GetString("TopBar_ViewMode_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string TopBar_ViewMode_Basic {
            get {
                return ResourceManager.GetString("TopBar_ViewMode_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Mode - Advanced parameters.
        /// </summary>
        public static string TopBar_ViewMode_ToolTip {
            get {
                return ResourceManager.GetString("TopBar_ViewMode_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [e-mail].
        /// </summary>
        public static string UserData_EmailPreview {
            get {
                return ResourceManager.GetString("UserData_EmailPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [last name].
        /// </summary>
        public static string UserData_LastNamePreview {
            get {
                return ResourceManager.GetString("UserData_LastNamePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [name].
        /// </summary>
        public static string UserData_NamePreview {
            get {
                return ResourceManager.GetString("UserData_NamePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [password].
        /// </summary>
        public static string UserData_PasswordPreview {
            get {
                return ResourceManager.GetString("UserData_PasswordPreview", resourceCulture);
            }
        }
    }
}
