//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authenticator.UI_WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Authenticator.UI_WPF.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string ageStart_ButtonNewsFeed {
            get {
                return ResourceManager.GetString("ageStart_ButtonNewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [m2].
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Building line.
        /// </summary>
        public static string BuildingLine {
            get {
                return ResourceManager.GetString("BuildingLine", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Boundary.
        /// </summary>
        public static string BuildingLine_Boundary {
            get {
                return ResourceManager.GetString("BuildingLine_Boundary", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        public static string BuildingLine_BoundaryButtonContent {
            get {
                return ResourceManager.GetString("BuildingLine_BoundaryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        public static string BuildingLine_Name {
            get {
                return ResourceManager.GetString("BuildingLine_Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Geometry.
        /// </summary>
        public static string BuildingLine_Shape {
            get {
                return ResourceManager.GetString("BuildingLine_Shape", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        public static string BuildingLine_ShapeButtonContent {
            get {
                return ResourceManager.GetString("BuildingLine_ShapeButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Building Dimensions.
        /// </summary>
        public static string BuildingProperties_Label {
            get {
                return ResourceManager.GetString("BuildingProperties_Label", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Building  Zone.
        /// </summary>
        public static string BuildingZone {
            get {
                return ResourceManager.GetString("BuildingZone", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Building Zone.
        /// </summary>
        public static string BuildingZone_Add {
            get {
                return ResourceManager.GetString("BuildingZone_Add", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Average count.
        /// </summary>
        public static string BuildingZone_AverageNumberOfLevels {
            get {
                return ResourceManager.GetString("BuildingZone_AverageNumberOfLevels", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Boundary.
        /// </summary>
        public static string BuildingZone_Boundary {
            get {
                return ResourceManager.GetString("BuildingZone_Boundary", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        public static string BuildingZone_BoundaryButtonContent {
            get {
                return ResourceManager.GetString("BuildingZone_BoundaryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Roof attic height.
        /// </summary>
        public static string BuildingZone_BuildingAtticHeight {
            get {
                return ResourceManager.GetString("BuildingZone_BuildingAtticHeight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu East-West axis depth.
        /// </summary>
        public static string BuildingZone_BuildingDepthEW {
            get {
                return ResourceManager.GetString("BuildingZone_BuildingDepthEW", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu North-South axis depth.
        /// </summary>
        public static string BuildingZone_BuildingDepthNS {
            get {
                return ResourceManager.GetString("BuildingZone_BuildingDepthNS", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string BuildingZone_BuildingGroundFloor {
            get {
                return ResourceManager.GetString("BuildingZone_BuildingGroundFloor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Floor heigth.
        /// </summary>
        public static string BuildingZone_BuildingHeightFloor {
            get {
                return ResourceManager.GetString("BuildingZone_BuildingHeightFloor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string BuildingZone_BuildingHeightFloorLast {
            get {
                return ResourceManager.GetString("BuildingZone_BuildingHeightFloorLast", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Length.
        /// </summary>
        public static string BuildingZone_BuildingLength {
            get {
                return ResourceManager.GetString("BuildingZone_BuildingLength", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string BuildingZone_BuildingLevelHeight {
            get {
                return ResourceManager.GetString("BuildingZone_BuildingLevelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Number of levels.
        /// </summary>
        public static string BuildingZone_BuildingNumberOfLevels {
            get {
                return ResourceManager.GetString("BuildingZone_BuildingNumberOfLevels", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Building orientation angle.
        /// </summary>
        public static string BuildingZone_BuildingOrientationAngle {
            get {
                return ResourceManager.GetString("BuildingZone_BuildingOrientationAngle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Acceptable building orientation angle deviation.
        /// </summary>
        public static string BuildingZone_BuildingOrientationAngleDeviation {
            get {
                return ResourceManager.GetString("BuildingZone_BuildingOrientationAngleDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Building dimensions.
        /// </summary>
        public static string BuildingZone_BuildingPropertiesHeader {
            get {
                return ResourceManager.GetString("BuildingZone_BuildingPropertiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Repetitive level height.
        /// </summary>
        public static string BuildingZone_FloorLevelHeight {
            get {
                return ResourceManager.GetString("BuildingZone_FloorLevelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Groundfloor heigth.
        /// </summary>
        public static string BuildingZone_GroundFloorLevelHeight {
            get {
                return ResourceManager.GetString("BuildingZone_GroundFloorLevelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Building height.
        /// </summary>
        public static string BuildingZone_HeightsHeader {
            get {
                return ResourceManager.GetString("BuildingZone_HeightsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Levels.
        /// </summary>
        public static string BuildingZone_LevelsHeader {
            get {
                return ResourceManager.GetString("BuildingZone_LevelsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Absolut maximum height.
        /// </summary>
        public static string BuildingZone_MaxAbsolutBuildingHeight {
            get {
                return ResourceManager.GetString("BuildingZone_MaxAbsolutBuildingHeight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Maximum level count.
        /// </summary>
        public static string BuildingZone_MaxNumberOfLevels {
            get {
                return ResourceManager.GetString("BuildingZone_MaxNumberOfLevels", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Maximum height.
        /// </summary>
        public static string BuildingZone_MaxRelativeBuildingHeight {
            get {
                return ResourceManager.GetString("BuildingZone_MaxRelativeBuildingHeight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Minimal average height.
        /// </summary>
        public static string BuildingZone_MinAverageBuildingHeight {
            get {
                return ResourceManager.GetString("BuildingZone_MinAverageBuildingHeight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Minimum height.
        /// </summary>
        public static string BuildingZone_MinBuildingHeight {
            get {
                return ResourceManager.GetString("BuildingZone_MinBuildingHeight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Minimium level count.
        /// </summary>
        public static string BuildingZone_MinNumberOfLevels {
            get {
                return ResourceManager.GetString("BuildingZone_MinNumberOfLevels", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        public static string BuildingZone_Name {
            get {
                return ResourceManager.GetString("BuildingZone_Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Thickness of external walls.
        /// </summary>
        public static string BuildingZone_NetInternalAreaExternalWalls {
            get {
                return ResourceManager.GetString("BuildingZone_NetInternalAreaExternalWalls", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Net internal area.
        /// </summary>
        public static string BuildingZone_NetInternalAreaHeader {
            get {
                return ResourceManager.GetString("BuildingZone_NetInternalAreaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Shaft ratio.
        /// </summary>
        public static string BuildingZone_NetInternalAreaShaftRatio {
            get {
                return ResourceManager.GetString("BuildingZone_NetInternalAreaShaftRatio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Parking hall area per one space.
        /// </summary>
        public static string BuildingZone_ParkingHallAreaPerSpace {
            get {
                return ResourceManager.GetString("BuildingZone_ParkingHallAreaPerSpace", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Parking structure.
        /// </summary>
        public static string BuildingZone_ParkingHeader {
            get {
                return ResourceManager.GetString("BuildingZone_ParkingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Additional places.
        /// </summary>
        public static string BuildingZone_ParkingSpaceAdditional {
            get {
                return ResourceManager.GetString("BuildingZone_ParkingSpaceAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Number of parking spaces per flat.
        /// </summary>
        public static string BuildingZone_ParkingSpacePerFlatRatio {
            get {
                return ResourceManager.GetString("BuildingZone_ParkingSpacePerFlatRatio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Number of parking spaces per 0-bedroom flat ratio.
        /// </summary>
        public static string BuildingZone_ParkingSpacePerM1Ratio {
            get {
                return ResourceManager.GetString("BuildingZone_ParkingSpacePerM1Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Number of parking spaces per  1-bedroom flat ratio.
        /// </summary>
        public static string BuildingZone_ParkingSpacePerM2Ratio {
            get {
                return ResourceManager.GetString("BuildingZone_ParkingSpacePerM2Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Number of parking spaces per 2-bedrooms flat ratio.
        /// </summary>
        public static string BuildingZone_ParkingSpacePerM3Ratio {
            get {
                return ResourceManager.GetString("BuildingZone_ParkingSpacePerM3Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Number of parking spaces per  3-bedrooms flat ratio.
        /// </summary>
        public static string BuildingZone_ParkingSpacePerM4Ratio {
            get {
                return ResourceManager.GetString("BuildingZone_ParkingSpacePerM4Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Number of parking spaces per  4-bedrooms flat ratio.
        /// </summary>
        public static string BuildingZone_ParkingSpacePerM5Ratio {
            get {
                return ResourceManager.GetString("BuildingZone_ParkingSpacePerM5Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Repetitive level height.
        /// </summary>
        public static string BuildingZone_RepetitveLevelHeight {
            get {
                return ResourceManager.GetString("BuildingZone_RepetitveLevelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Flat structure.
        /// </summary>
        public static string BuildingZone_StructureHeader {
            get {
                return ResourceManager.GetString("BuildingZone_StructureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Top floor level heigth.
        /// </summary>
        public static string BuildingZone_TopFloorLevelHeight {
            get {
                return ResourceManager.GetString("BuildingZone_TopFloorLevelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Top level height.
        /// </summary>
        public static string BuildingZone_TopLevelHeight {
            get {
                return ResourceManager.GetString("BuildingZone_TopLevelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Example project.
        /// </summary>
        public static string ButtonExampleProject {
            get {
                return ResourceManager.GetString("ButtonExampleProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open example project from Kolega.
        /// </summary>
        public static string ButtonExampleProject_ToolTip {
            get {
                return ResourceManager.GetString("ButtonExampleProject_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Simple Site Example Project.
        /// </summary>
        public static string ButtonExampleProject1 {
            get {
                return ResourceManager.GetString("ButtonExampleProject1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open example project.
        /// </summary>
        public static string ButtonExampleProject1_Tooltip {
            get {
                return ResourceManager.GetString("ButtonExampleProject1_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Standard Site Example Project.
        /// </summary>
        public static string ButtonExampleProject2 {
            get {
                return ResourceManager.GetString("ButtonExampleProject2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open example project.
        /// </summary>
        public static string ButtonExampleProject2_Tooltip {
            get {
                return ResourceManager.GetString("ButtonExampleProject2_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Complex Site Example Project.
        /// </summary>
        public static string ButtonExampleProject3 {
            get {
                return ResourceManager.GetString("ButtonExampleProject3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open example project.
        /// </summary>
        public static string ButtonExampleProject3_Tooltip {
            get {
                return ResourceManager.GetString("ButtonExampleProject3_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Next step: Architecture.
        /// </summary>
        public static string ButtonGoNextArchitecture {
            get {
                return ResourceManager.GetString("ButtonGoNextArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Next step: Compare.
        /// </summary>
        public static string ButtonGoNextCompare {
            get {
                return ResourceManager.GetString("ButtonGoNextCompare", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Next step.
        /// </summary>
        public static string ButtonGoNextGenerate {
            get {
                return ResourceManager.GetString("ButtonGoNextGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New project.
        /// </summary>
        public static string ButtonNewProject {
            get {
                return ResourceManager.GetString("ButtonNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create new project with Kolega.
        /// </summary>
        public static string ButtonNewProject_ToolTip {
            get {
                return ResourceManager.GetString("ButtonNewProject_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open project.
        /// </summary>
        public static string ButtonOpenProject {
            get {
                return ResourceManager.GetString("ButtonOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open existing project from Kolega.
        /// </summary>
        public static string ButtonOpenProject_ToolTip {
            get {
                return ResourceManager.GetString("ButtonOpenProject_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Back to Solutions List.
        /// </summary>
        public static string ButtonSolutionGoBack {
            get {
                return ResourceManager.GetString("ButtonSolutionGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Check Zone.
        /// </summary>
        public static string CheckZone {
            get {
                return ResourceManager.GetString("CheckZone", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Check Zone.
        /// </summary>
        public static string CheckZone_Add {
            get {
                return ResourceManager.GetString("CheckZone_Add", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Boundary.
        /// </summary>
        public static string CheckZone_Boundary {
            get {
                return ResourceManager.GetString("CheckZone_Boundary", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        public static string CheckZone_BoundaryButtonContent {
            get {
                return ResourceManager.GetString("CheckZone_BoundaryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string CheckZone_BuildingCoverageRatio {
            get {
                return ResourceManager.GetString("CheckZone_BuildingCoverageRatio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Building coverage.
        /// </summary>
        public static string CheckZone_BuildingCoverageRatioHeader {
            get {
                return ResourceManager.GetString("CheckZone_BuildingCoverageRatioHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Floor area ratio.
        /// </summary>
        public static string CheckZone_FloorAreaRatio {
            get {
                return ResourceManager.GetString("CheckZone_FloorAreaRatio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string CheckZone_FloorAreaRatioHeader {
            get {
                return ResourceManager.GetString("CheckZone_FloorAreaRatioHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Maximum ratio.
        /// </summary>
        public static string CheckZone_MaxBuildingCoverageRatio {
            get {
                return ResourceManager.GetString("CheckZone_MaxBuildingCoverageRatio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string CheckZone_MaxFloorAreaRatio {
            get {
                return ResourceManager.GetString("CheckZone_MaxFloorAreaRatio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total.
        /// </summary>
        public static string CheckZone_MaxFloorAreaRatioAboveAndUnderground {
            get {
                return ResourceManager.GetString("CheckZone_MaxFloorAreaRatioAboveAndUnderground", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Maximum above ground.
        /// </summary>
        public static string CheckZone_MaxFloorAreaRatioAboveGround {
            get {
                return ResourceManager.GetString("CheckZone_MaxFloorAreaRatioAboveGround", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Floor area ratio.
        /// </summary>
        public static string CheckZone_MaxFloorAreaRatioHeader {
            get {
                return ResourceManager.GetString("CheckZone_MaxFloorAreaRatioHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Maximum underground.
        /// </summary>
        public static string CheckZone_MaxFloorAreaRatioUnderground {
            get {
                return ResourceManager.GetString("CheckZone_MaxFloorAreaRatioUnderground", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        public static string CheckZone_Name {
            get {
                return ResourceManager.GetString("CheckZone_Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total.
        /// </summary>
        public static string CheckZone_TotalFloorAreaRatio {
            get {
                return ResourceManager.GetString("CheckZone_TotalFloorAreaRatio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Maximum underground.
        /// </summary>
        public static string CheckZone_UndergroundFloorAreaRatio {
            get {
                return ResourceManager.GetString("CheckZone_UndergroundFloorAreaRatio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kolega is working. It&apos;s coffee time for you..
        /// </summary>
        public static string CommunicationWaitingLong {
            get {
                return ResourceManager.GetString("CommunicationWaitingLong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Existing coverage area.
        /// </summary>
        public static string Context_ContextBuildingsCoverageArea {
            get {
                return ResourceManager.GetString("Context_ContextBuildingsCoverageArea", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Existing buildings on site.
        /// </summary>
        public static string Context_ContextBuildingsHeader {
            get {
                return ResourceManager.GetString("Context_ContextBuildingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Include in the calculation.
        /// </summary>
        public static string Context_ContextBuildingsIncludeInCalculation {
            get {
                return ResourceManager.GetString("Context_ContextBuildingsIncludeInCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Existing total area.
        /// </summary>
        public static string Context_ContextBuildingsTotalArea {
            get {
                return ResourceManager.GetString("Context_ContextBuildingsTotalArea", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Existing buildings.
        /// </summary>
        public static string Context_ContextExistingBuildings {
            get {
                return ResourceManager.GetString("Context_ContextExistingBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Context.
        /// </summary>
        public static string Context_ContextHeader {
            get {
                return ResourceManager.GetString("Context_ContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Direction.
        /// </summary>
        public static string Context_ContextParcelDivisionDirection {
            get {
                return ResourceManager.GetString("Context_ContextParcelDivisionDirection", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Parcel division.
        /// </summary>
        public static string Context_ContextParcelDivisionHeader {
            get {
                return ResourceManager.GetString("Context_ContextParcelDivisionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Terrain.
        /// </summary>
        public static string Context_ContextTerrain {
            get {
                return ResourceManager.GetString("Context_ContextTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Excluded Zone.
        /// </summary>
        public static string Context_ExcludedZoneAdd {
            get {
                return ResourceManager.GetString("Context_ExcludedZoneAdd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add surrounding.
        /// </summary>
        public static string Context_SurroundingAdd {
            get {
                return ResourceManager.GetString("Context_SurroundingAdd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add terrain.
        /// </summary>
        public static string Context_TerrainAdd {
            get {
                return ResourceManager.GetString("Context_TerrainAdd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        public static string ExcludedZone_BoundaryButtonContent {
            get {
                return ResourceManager.GetString("ExcludedZone_BoundaryButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zone excluded from development.
        /// </summary>
        public static string ExcludedZone_ExcludedZoneHeader {
            get {
                return ResourceManager.GetString("ExcludedZone_ExcludedZoneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        public static string ExcludedZone_ExcludedZoneName {
            get {
                return ResourceManager.GetString("ExcludedZone_ExcludedZoneName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 0-bedroom.
        /// </summary>
        public static string Flat0Bedroom {
            get {
                return ResourceManager.GetString("Flat0Bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 1-bedroom.
        /// </summary>
        public static string Flat1Bedroom {
            get {
                return ResourceManager.GetString("Flat1Bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 2-bedroom.
        /// </summary>
        public static string Flat2Bedrooms {
            get {
                return ResourceManager.GetString("Flat2Bedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 3-bedroom.
        /// </summary>
        public static string Flat3Bedrooms {
            get {
                return ResourceManager.GetString("Flat3Bedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 4-bedroom.
        /// </summary>
        public static string Flat4Bedrooms {
            get {
                return ResourceManager.GetString("Flat4Bedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Report bug.
        /// </summary>
        public static string FooterBugReport {
            get {
                return ResourceManager.GetString("FooterBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu kolega.space.
        /// </summary>
        public static string FooterKolegaSite {
            get {
                return ResourceManager.GetString("FooterKolegaSite", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add suggestion.
        /// </summary>
        public static string FooterSurveySuggestion {
            get {
                return ResourceManager.GetString("FooterSurveySuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User Guide.
        /// </summary>
        public static string FooterUserGuide {
            get {
                return ResourceManager.GetString("FooterUserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Log out.
        /// </summary>
        public static string GoToProfile {
            get {
                return ResourceManager.GetString("GoToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu max.
        /// </summary>
        public static string Interval_End {
            get {
                return ResourceManager.GetString("Interval_End", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu min.
        /// </summary>
        public static string Interval_Start {
            get {
                return ResourceManager.GetString("Interval_Start", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [m].
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string LocalizationOnEarth_Latitude {
            get {
                return ResourceManager.GetString("LocalizationOnEarth_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string LocalizationOnEarth_Longitude {
            get {
                return ResourceManager.GetString("LocalizationOnEarth_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [°].
        /// </summary>
        public static string LocationDegree {
            get {
                return ResourceManager.GetString("LocationDegree", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Location.
        /// </summary>
        public static string LocationOnEarth {
            get {
                return ResourceManager.GetString("LocationOnEarth", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Location on map.
        /// </summary>
        public static string LocationOnEarth_CheckLocation {
            get {
                return ResourceManager.GetString("LocationOnEarth_CheckLocation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Check.
        /// </summary>
        public static string LocationOnEarth_CheckLocationButton {
            get {
                return ResourceManager.GetString("LocationOnEarth_CheckLocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Latitude.
        /// </summary>
        public static string LocationOnEarth_Latitude {
            get {
                return ResourceManager.GetString("LocationOnEarth_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Longitude.
        /// </summary>
        public static string LocationOnEarth_Longitude {
            get {
                return ResourceManager.GetString("LocationOnEarth_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete item.
        /// </summary>
        public static string Manage_DeleteItem {
            get {
                return ResourceManager.GetString("Manage_DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sign In with Apple.
        /// </summary>
        public static string ModalLogin_ButtonAppleLogin {
            get {
                return ResourceManager.GetString("ModalLogin_ButtonAppleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Change.
        /// </summary>
        public static string ModalLogin_ButtonChangePassword {
            get {
                return ResourceManager.GetString("ModalLogin_ButtonChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sign In with Google.
        /// </summary>
        public static string ModalLogin_ButtonGoogleLogin {
            get {
                return ResourceManager.GetString("ModalLogin_ButtonGoogleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sign In.
        /// </summary>
        public static string ModalLogin_ButtonLogin {
            get {
                return ResourceManager.GetString("ModalLogin_ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sing up.
        /// </summary>
        public static string ModalLogin_ButtonSignUp {
            get {
                return ResourceManager.GetString("ModalLogin_ButtonSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Forgot your password?.
        /// </summary>
        public static string ModalLogin_ChangePasswordText {
            get {
                return ResourceManager.GetString("ModalLogin_ChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Don&apos;t have an account yet?.
        /// </summary>
        public static string ModalLogin_SignUpText {
            get {
                return ResourceManager.GetString("ModalLogin_SignUpText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sing in to your account.
        /// </summary>
        public static string ModalLogin_SubTitle {
            get {
                return ResourceManager.GetString("ModalLogin_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu or.
        /// </summary>
        public static string ModalLogin_Text1 {
            get {
                return ResourceManager.GetString("ModalLogin_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Say Hi to Kolega..
        /// </summary>
        public static string ModalLogin_Title {
            get {
                return ResourceManager.GetString("ModalLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Go back to login.
        /// </summary>
        public static string ModalPasswordChanged_ButtonGoBackToLogin {
            get {
                return ResourceManager.GetString("ModalPasswordChanged_ButtonGoBackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Check your email inbox. Follow the link and set a new password following the instructions in the message from us..
        /// </summary>
        public static string ModalPasswordChanged_CheckEmailText {
            get {
                return ResourceManager.GetString("ModalPasswordChanged_CheckEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu We have sent you an email to change your password..
        /// </summary>
        public static string ModalPasswordChanged_SubTitle {
            get {
                return ResourceManager.GetString("ModalPasswordChanged_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reset password.
        /// </summary>
        public static string ModalPasswordChanged_Title {
            get {
                return ResourceManager.GetString("ModalPasswordChanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Go Back.
        /// </summary>
        public static string ModalRegister_ButtonCancle {
            get {
                return ResourceManager.GetString("ModalRegister_ButtonCancle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create an account.
        /// </summary>
        public static string ModalRegister_ButtonRegister {
            get {
                return ResourceManager.GetString("ModalRegister_ButtonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create an account.
        /// </summary>
        public static string ModalRegister_SubTitle {
            get {
                return ResourceManager.GetString("ModalRegister_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Say Hi to Kolega!.
        /// </summary>
        public static string ModalRegister_Title {
            get {
                return ResourceManager.GetString("ModalRegister_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Go to login.
        /// </summary>
        public static string ModalRegistered_ButtonGoBackToLogin {
            get {
                return ResourceManager.GetString("ModalRegistered_ButtonGoBackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Resend.
        /// </summary>
        public static string ModalRegistered_ButtonSendAgain {
            get {
                return ResourceManager.GetString("ModalRegistered_ButtonSendAgain", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Check your email for a verification link and log in..
        /// </summary>
        public static string ModalRegistered_CheckEmailText {
            get {
                return ResourceManager.GetString("ModalRegistered_CheckEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Haven&apos;t recived verification email?.
        /// </summary>
        public static string ModalRegistered_NoEmailRevicedText {
            get {
                return ResourceManager.GetString("ModalRegistered_NoEmailRevicedText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Verification email sent.
        /// </summary>
        public static string ModalRegistered_SubTitle {
            get {
                return ResourceManager.GetString("ModalRegistered_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Meet your new Kolega!.
        /// </summary>
        public static string ModalRegistered_Title {
            get {
                return ResourceManager.GetString("ModalRegistered_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Define the spatial parameters of the development..
        /// </summary>
        public static string PageArchitectureInput_Description {
            get {
                return ResourceManager.GetString("PageArchitectureInput_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 03.
        /// </summary>
        public static string PageArchitectureInput_Number {
            get {
                return ResourceManager.GetString("PageArchitectureInput_Number", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string PageArchitectureInput_StructureDisplayParkingAreaProperty {
            get {
                return ResourceManager.GetString("PageArchitectureInput_StructureDisplayParkingAreaProperty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Architecture.
        /// </summary>
        public static string PageArchitectureInput_Title {
            get {
                return ResourceManager.GetString("PageArchitectureInput_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Compile information from different solutions..
        /// </summary>
        public static string PageCompare_Description {
            get {
                return ResourceManager.GetString("PageCompare_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 07.
        /// </summary>
        public static string PageCompare_Number {
            get {
                return ResourceManager.GetString("PageCompare_Number", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Compare.
        /// </summary>
        public static string PageCompare_Title {
            get {
                return ResourceManager.GetString("PageCompare_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save the solutions and reports..
        /// </summary>
        public static string PageExport_Description {
            get {
                return ResourceManager.GetString("PageExport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 08.
        /// </summary>
        public static string PageExport_Number {
            get {
                return ResourceManager.GetString("PageExport_Number", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Export.
        /// </summary>
        public static string PageExport_Title {
            get {
                return ResourceManager.GetString("PageExport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start generating design options..
        /// </summary>
        public static string PageGenerate_Description {
            get {
                return ResourceManager.GetString("PageGenerate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start generating.
        /// </summary>
        public static string PageGenerate_GenerateButtonContent {
            get {
                return ResourceManager.GetString("PageGenerate_GenerateButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Generate no longer than.
        /// </summary>
        public static string PageGenerate_MaxTime {
            get {
                return ResourceManager.GetString("PageGenerate_MaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 04.
        /// </summary>
        public static string PageGenerate_Number {
            get {
                return ResourceManager.GetString("PageGenerate_Number", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Maximum number of solutions.
        /// </summary>
        public static string PageGenerate_NumberOfSolutions {
            get {
                return ResourceManager.GetString("PageGenerate_NumberOfSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Optimize geometry.
        /// </summary>
        public static string PageGenerate_OptimizeSwitch {
            get {
                return ResourceManager.GetString("PageGenerate_OptimizeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Progress.
        /// </summary>
        public static string PageGenerate_Progress {
            get {
                return ResourceManager.GetString("PageGenerate_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Generate.
        /// </summary>
        public static string PageGenerate_Title {
            get {
                return ResourceManager.GetString("PageGenerate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter your location and immediate surroundings..
        /// </summary>
        public static string PageSiteInput_Description {
            get {
                return ResourceManager.GetString("PageSiteInput_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 02.
        /// </summary>
        public static string PageSiteInput_Number {
            get {
                return ResourceManager.GetString("PageSiteInput_Number", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Site Input.
        /// </summary>
        public static string PageSiteInput_Title {
            get {
                return ResourceManager.GetString("PageSiteInput_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Solution filter.
        /// </summary>
        public static string PageSolution_FilterHeader {
            get {
                return ResourceManager.GetString("PageSolution_FilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 05.
        /// </summary>
        public static string PageSolution_Number {
            get {
                return ResourceManager.GetString("PageSolution_Number", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Minimum Building Footprint Area.
        /// </summary>
        public static string PageSolution_OutputBAMax {
            get {
                return ResourceManager.GetString("PageSolution_OutputBAMax", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Building area.
        /// </summary>
        public static string PageSolution_OutputBuildingArea {
            get {
                return ResourceManager.GetString("PageSolution_OutputBuildingArea", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Achieved daylight ratio.
        /// </summary>
        public static string PageSolution_OutputDaylight {
            get {
                return ResourceManager.GetString("PageSolution_OutputDaylight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Minimum daylight ratio.
        /// </summary>
        public static string PageSolution_OutputDaylightMax {
            get {
                return ResourceManager.GetString("PageSolution_OutputDaylightMax", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Minimum Floor Area.
        /// </summary>
        public static string PageSolution_OutputFAMax {
            get {
                return ResourceManager.GetString("PageSolution_OutputFAMax", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total floor area.
        /// </summary>
        public static string PageSolution_OutputFloorArea {
            get {
                return ResourceManager.GetString("PageSolution_OutputFloorArea", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Achieved obstruction ratio.
        /// </summary>
        public static string PageSolution_OutputObstruction {
            get {
                return ResourceManager.GetString("PageSolution_OutputObstruction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Minimum obstruction ratio.
        /// </summary>
        public static string PageSolution_OutputObstructionMax {
            get {
                return ResourceManager.GetString("PageSolution_OutputObstructionMax", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sorting solutions.
        /// </summary>
        public static string PageSolution_SortingHeader {
            get {
                return ResourceManager.GetString("PageSolution_SortingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show starred only.
        /// </summary>
        public static string PageSolution_StarOnly {
            get {
                return ResourceManager.GetString("PageSolution_StarOnly", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Solution.
        /// </summary>
        public static string PageSolution_Title {
            get {
                return ResourceManager.GetString("PageSolution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Review the design options received..
        /// </summary>
        public static string PageSolutions_Description {
            get {
                return ResourceManager.GetString("PageSolutions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 05.
        /// </summary>
        public static string PageSolutions_Number {
            get {
                return ResourceManager.GetString("PageSolutions_Number", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Solutions.
        /// </summary>
        public static string PageSolutions_Title {
            get {
                return ResourceManager.GetString("PageSolutions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add file localization.
        /// </summary>
        public static string PageStart_AddPath {
            get {
                return ResourceManager.GetString("PageStart_AddPath", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Read more.
        /// </summary>
        public static string PageStart_ButtonNewsFeed {
            get {
                return ResourceManager.GetString("PageStart_ButtonNewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start working with Kolega. Create or continue a project..
        /// </summary>
        public static string PageStart_Description {
            get {
                return ResourceManager.GetString("PageStart_Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        public static string PageStart_NewProjectCancel {
            get {
                return ResourceManager.GetString("PageStart_NewProjectCancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel project creation.
        /// </summary>
        public static string PageStart_NewProjectCancelTooltip {
            get {
                return ResourceManager.GetString("PageStart_NewProjectCancelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create.
        /// </summary>
        public static string PageStart_NewProjectCreate {
            get {
                return ResourceManager.GetString("PageStart_NewProjectCreate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create a new project.
        /// </summary>
        public static string PageStart_NewProjectCreateTooltip {
            get {
                return ResourceManager.GetString("PageStart_NewProjectCreateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Project.
        /// </summary>
        public static string PageStart_NewProjectTitle {
            get {
                return ResourceManager.GetString("PageStart_NewProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Software that enables the generation of solutions for a specific plot of land - urban layouts and floor plans based on the given parameters of the project..
        /// </summary>
        public static string PageStart_NewsFeedItem {
            get {
                return ResourceManager.GetString("PageStart_NewsFeedItem", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu We are excited to announce the launch of the Kolega! This innovative app is designed to streamline architectural workflows, enhance collaboration, and boost productivity for architects worldwide. With features like real-time project sharing, 3D modeling tools, and integrated project management, the Kolega App is set to revolutionize the way architects work..
        /// </summary>
        public static string PageStart_NewsFeedItem1 {
            get {
                return ResourceManager.GetString("PageStart_NewsFeedItem1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Architects from around the globe are already praising the Kolega App&apos;s intuitive interface and powerful features. By leveraging the latest in technology, Kolega empowers architects to bring their visions to life with unprecedented ease. Stay tuned for success stories and updates from architects who have adopted Kolega as their go-to tool..
        /// </summary>
        public static string PageStart_NewsFeedItem2 {
            get {
                return ResourceManager.GetString("PageStart_NewsFeedItem2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you an architect looking to simplify your work and enhance your designs? Join the Kolega community today and experience the future of architectural software..
        /// </summary>
        public static string PageStart_NewsFeedItem3 {
            get {
                return ResourceManager.GetString("PageStart_NewsFeedItem3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your new digital partner in design..
        /// </summary>
        public static string PageStart_NewsFeedSubTitle {
            get {
                return ResourceManager.GetString("PageStart_NewsFeedSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Meet Kolega..
        /// </summary>
        public static string PageStart_NewsFeedTitle {
            get {
                return ResourceManager.GetString("PageStart_NewsFeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Introducing Kolega.
        /// </summary>
        public static string PageStart_NewsFeedTitle1 {
            get {
                return ResourceManager.GetString("PageStart_NewsFeedTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Embrace the Future.
        /// </summary>
        public static string PageStart_NewsFeedTitle2 {
            get {
                return ResourceManager.GetString("PageStart_NewsFeedTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Join the Community Today!.
        /// </summary>
        public static string PageStart_NewsFeedTitle3 {
            get {
                return ResourceManager.GetString("PageStart_NewsFeedTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 01.
        /// </summary>
        public static string PageStart_Number {
            get {
                return ResourceManager.GetString("PageStart_Number", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Recent projects.
        /// </summary>
        public static string PageStart_RecentProjectsTitle {
            get {
                return ResourceManager.GetString("PageStart_RecentProjectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sub Test EN.
        /// </summary>
        public static string PageStart_Subtitle {
            get {
                return ResourceManager.GetString("PageStart_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start project.
        /// </summary>
        public static string PageStart_Title {
            get {
                return ResourceManager.GetString("PageStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 02.
        /// </summary>
        public static string PageUrbanInput_Number {
            get {
                return ResourceManager.GetString("PageUrbanInput_Number", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Input.
        /// </summary>
        public static string PageUrbanInput_SubTitle {
            get {
                return ResourceManager.GetString("PageUrbanInput_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Urban Input.
        /// </summary>
        public static string PageUrbanInput_Title {
            get {
                return ResourceManager.GetString("PageUrbanInput_Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Site Data.
        /// </summary>
        public static string ProjectData {
            get {
                return ResourceManager.GetString("ProjectData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Analysis Settings.
        /// </summary>
        public static string ProjectData_AnalysisHeader {
            get {
                return ResourceManager.GetString("ProjectData_AnalysisHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Analyze Obstruction.
        /// </summary>
        public static string ProjectData_AnalyzeObstruction {
            get {
                return ResourceManager.GetString("ProjectData_AnalyzeObstruction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Flat area ratio.
        /// </summary>
        public static string ProjectData_FlatsAreaRatio {
            get {
                return ResourceManager.GetString("ProjectData_FlatsAreaRatio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Flat Settings.
        /// </summary>
        public static string ProjectData_FlatSettings {
            get {
                return ResourceManager.GetString("ProjectData_FlatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Area Settings.
        /// </summary>
        public static string ProjectData_FlatSettingsHeader {
            get {
                return ResourceManager.GetString("ProjectData_FlatSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Downtown.
        /// </summary>
        public static string ProjectData_IsDowntown {
            get {
                return ResourceManager.GetString("ProjectData_IsDowntown", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Location.
        /// </summary>
        public static string ProjectData_LocationHeader {
            get {
                return ResourceManager.GetString("ProjectData_LocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dayligth Settings.
        /// </summary>
        public static string ProjectData_TimeRequirements {
            get {
                return ResourceManager.GetString("ProjectData_TimeRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu True North angle.
        /// </summary>
        public static string ProjectData_TrueNorth {
            get {
                return ResourceManager.GetString("ProjectData_TrueNorth", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [deg].
        /// </summary>
        public static string Radians {
            get {
                return ResourceManager.GetString("Radians", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu %.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu null.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Parking Space Area.
        /// </summary>
        public static string StructureDisplay_ParkingAreaProperty {
            get {
                return ResourceManager.GetString("StructureDisplay_ParkingAreaProperty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Surroundings.
        /// </summary>
        public static string Surrounding {
            get {
                return ResourceManager.GetString("Surrounding", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Context name.
        /// </summary>
        public static string Surrounding_Name {
            get {
                return ResourceManager.GetString("Surrounding_Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Time requierd                   .
        /// </summary>
        public static string TimeRequirementViewModel_TimeSpanToPassPreview {
            get {
                return ResourceManager.GetString("TimeRequirementViewModel_TimeSpanToPassPreview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Advanced.
        /// </summary>
        public static string TopBar_ViewMode_Advanced {
            get {
                return ResourceManager.GetString("TopBar_ViewMode_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Basic.
        /// </summary>
        public static string TopBar_ViewMode_Basic {
            get {
                return ResourceManager.GetString("TopBar_ViewMode_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User Mode - Advanced parameters.
        /// </summary>
        public static string TopBar_ViewMode_ToolTip {
            get {
                return ResourceManager.GetString("TopBar_ViewMode_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [e-mail].
        /// </summary>
        public static string UserData_EmailPreview {
            get {
                return ResourceManager.GetString("UserData_EmailPreview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [last name].
        /// </summary>
        public static string UserData_LastNamePreview {
            get {
                return ResourceManager.GetString("UserData_LastNamePreview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [name].
        /// </summary>
        public static string UserData_NamePreview {
            get {
                return ResourceManager.GetString("UserData_NamePreview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu [password].
        /// </summary>
        public static string UserData_PasswordPreview {
            get {
                return ResourceManager.GetString("UserData_PasswordPreview", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Export.
        /// </summary>
        public static string ViewSettings_Export {
            get {
                return ResourceManager.GetString("ViewSettings_Export", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show all.
        /// </summary>
        public static string ViewSettings_ShowAllTooltip {
            get {
                return ResourceManager.GetString("ViewSettings_ShowAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Measuring points.
        /// </summary>
        public static string ViewSettings_ViewAnalytical {
            get {
                return ResourceManager.GetString("ViewSettings_ViewAnalytical", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Daylight.
        /// </summary>
        public static string ViewSettings_ViewDaylight {
            get {
                return ResourceManager.GetString("ViewSettings_ViewDaylight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Flats.
        /// </summary>
        public static string ViewSettings_ViewFlats {
            get {
                return ResourceManager.GetString("ViewSettings_ViewFlats", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Input.
        /// </summary>
        public static string ViewSettings_ViewInput {
            get {
                return ResourceManager.GetString("ViewSettings_ViewInput", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Masses.
        /// </summary>
        public static string ViewSettings_ViewMass {
            get {
                return ResourceManager.GetString("ViewSettings_ViewMass", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Obstruction.
        /// </summary>
        public static string ViewSettings_ViewObstruction {
            get {
                return ResourceManager.GetString("ViewSettings_ViewObstruction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wireframes.
        /// </summary>
        public static string ViewSettings_ViewWireframe {
            get {
                return ResourceManager.GetString("ViewSettings_ViewWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        public static string ViewSettings_Wireframe {
            get {
                return ResourceManager.GetString("ViewSettings_Wireframe", resourceCulture);
            }
        }
    }
}
